### PR TITLE
42 rebase add special handling to images that have geometric inconsistencies

### PR DESCRIPTION
**Pull request by naucoin**
BUG: recover from selecting segmentation with wrong geometry
    
Offer to the user the option of resampling the chosen segmentation,
preserving any labels in it, to create a new label volume for the segmentation.
Added a new helper class for a popup question, returns True or False for a Yes or No
answer.

Call the volumes logic method CheckForLabelVolumeValidity to get a
verbose message string if the label map and scalar volumes don't
match geometry wise. An empty string means that they match, otherwise
print it out in the error message box.

Remove GeometriesMatch since we're now using the more extensive volumes
logic volumesLogic.CheckForLabelVolumeValidity
  
Update script to check geometry before resampling, add a geometry check and
only resample if necessary. Still use the BRAINS resample, the volumes logic
resample doesn't enforce the ushort output type.

Issue #42

### CODE REVIEW

**Comment by fedorov** [comment]
Nicole, looks good to me!

One suggestion: I think it makes sense to change the converter script to use the same resampling mechanism as done in the module (right now the script is using BRAINS, and the module is using Volumes logic). This way we (hopefully) make sure there is no incidental inconsistency while converting the label using GUI and the script, and also make the code more symmetric. 

How about we just cast the input label to ushort in the converter script, and then call Volumes resample? Or is there something else I didn't think of?

**Comment by naucoin** [comment]
I double checked the volumes logic resample, it will use nearest neighbour interpolation if the input volume is a label map, and that flag is already set. 
As long as the input volume is ushort, the output will be as well. The label volume is created as a new vtkMRMLScalarVolumeNode that's been flagged as a label volume after reading in the data from disk. Doesn't look like in the node that it triggers any re-sampling, so we'll have to do that before passing it in.

**Comment by naucoin** [comment]
Committed the change to use the volumes logic resampling and volumes info widget type conversion.

**Comment by naucoin** [comment]
Thanks! I'll see if I can get the dashboard cleaned up as well.

**Comment by fedorov** [comment]
Nicole, are you planning to update ExtensionIndex?

**Comment by naucoin** [comment]
Extensions index pull request:
https://github.com/Slicer/ExtensionsIndex/pull/936

**Comment by naucoin** [comment]
A couple of tests are failing due to the logging change in Reporting:
https://github.com/fedorov/Reporting/commit/7b99e96fc1374cf5c972dab78dd5f6de793fa15e
http://slicer.cdash.org/testDetails.php?test=6164083&build=410553

**Comment by fedorov** [comment]
Thanks!

**Comment by naucoin** [comment]
ReportingRoundTripTest: after adding the import logging call, digging into why the fiducial is at the wrong place: when the DICOM volume gets loaded back in from the report, it's IJK2RAS matrix is identity, instead of what it was when it was originally loaded. Therefore the conversion of the fiducial from the slice's display coordinates to RAS is failing. Digging into why the matrix is missing on reload.
Also: have to update to Markups fiducials at some point.

**Pull request merged**
